status = [
  "buildkite/iohk-ops",
  "ci/hydra:serokell:iohk-ops:iohk-ops.x86_64-linux",
  "ci/hydra:serokell:iohk-ops:iohk-ops-integration-test.x86_64-linux",
  "ci/hydra:serokell:iohk-ops:checks.shellcheck",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
