steps:
  - label: 'iohk-ops'
    command: 'scripts/ci.hs'
    agents:
      - "system=x86_64-linux"
    env:
      NIX_REMOTE: daemon
    agents:
      system: x86_64-linux
  - label: 'iohk-ops-shellcheck'
    command: 'scripts/shellcheck.sh'
    agents:
      - "system=x86_64-linux"
    env:
      NIX_REMOTE: daemon
    agents:
      system: x86_64-linux
